name: ebroker #! DO NOT CHANGE THIS
description: Welcome to eBroker.

publish_to: 'none'
version: 1.3.0+74

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core UI & Charts
  carousel_slider: ^4.2.1
  custom_refresh_indicator: ^3.0.0
  dotted_border: ^2.1.0
  flutter_widget_from_html: ^0.14.11
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.2.0
  nested: ^1.0.0

  # Firebase Services
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19

  # Authentication & Sign-in
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0

  # Media & Visuals
  cached_network_image: ^3.3.1
  flick_video_player: ^0.8.0
  flutter_image_compress: ^2.2.0
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  panorama_viewer: ^1.0.3
  video_player: ^2.8.3
  youtube_player_flutter: ^9.0.0

  # Audio
  just_audio: ^0.9.36
  record: ^5.0.4

  # Animations
  lottie: ^3.1.0
  shimmer: ^3.0.0

  # Networking & HTTP
  connectivity_plus: ^5.0.2
  dio: ^5.4.1
  http: ^1.2.1
  http_parser: ^4.0.2

  # State Management & Storage
  flutter_bloc: ^8.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # Location & Maps
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.0
  webview_flutter: ^4.7.0

  # Pickers & Input
  country_picker: ^2.0.26
  file_picker: ^8.0.0+1
  sms_autofill: ^2.3.0

  # Utilities & Tools
  device_info_plus: ^10.1.0
  encrypt: ^5.0.3
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  open_filex: ^4.4.0
  package_info_plus: ^7.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  printing: ^5.12.0
  share_plus: ^9.0.0
  timeago: ^3.6.1
  url_launcher: ^6.2.5
  very_good_analysis: ^5.1.0
  pointycastle: ^3.7.4
  
  # Payment Gateways
  in_app_purchase: ^3.2.0

  # Notifications & Reviews
  awesome_notifications: ^0.9.3+1
  google_mobile_ads: ^5.0.0
  in_app_review: ^2.0.8

  # PDF Generation
  flutter_html_to_pdf: ^0.7.0

  collection: ^1.18.0
  table_calendar: ^3.1.0
  timezone: ^0.9.2
  persistent_bottom_nav_bar_v2: ^4.2.8
  dot_shorthand_converter: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icons/ic_launcher.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/app_icons/
    - assets/languages/
    - assets/lottie/
    - assets/chat_background/
    - assets/svg/MultiColorSvg/
    - assets/svg/social_media/
    - assets/svg/Fallback/
    - assets/city.jpg
    - assets/map.png
    - assets/location_rent.png
    - assets/location_sell.png
    - assets/location_selected.png
    - assets/map_styles/

  fonts:
    - family: PrimaryFont 
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
